version: '3.8'

services:
  mancy-ai:
    build: .
    container_name: mancy-ai
    restart: unless-stopped
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./memory-db.json:/app/memory-db.json
      - ./qlyte-db.json:/app/qlyte-db.json
      - ./uploads:/app/uploads
      - ./public:/app/public
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M